# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map.
# clear_everything - If this is set, we will clear everything before loading the map.


# The core directory we will locate our templates at, best not to change this.
directory = "_maps/skyrat/automapper/templates/"

# METASTATION MAP TEMPLATES
# Metastation Arrivals
[templates.metastaton_arrivals]
map_files = ["metastation_arrivals.dmm"]
required_map = "MetaStation"
coordinates = [20, 107, 1]

# Metastation Orderly Post
[templates.metastation_orderly_post]
map_files = ["metastation_orderly_post.dmm"]
required_map = "MetaStation"
coordinates = [92, 107, 1]

# Metastation Science Post
[templates.metastation_science_post]
map_files = ["metastation_science_post.dmm"]
required_map = "MetaStation"
coordinates = [123, 95, 1]

# Metastation Engineering Post
[templates.metastation_engineering_post]
map_files = ["metastation_engineering_post.dmm"]
required_map = "MetaStation"
coordinates = [164, 131, 1]

# Metastation Cargo Post
[templates.metastation_cargo_post]
map_files = ["metastation_cargo_post.dmm"]
required_map = "MetaStation"
coordinates = [71, 155, 1]

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo.dmm"]
required_map = "MetaStation"
coordinates = [136, 181, 1]

# Metastation Barber
[templates.metastation_barber]
map_files = ["metastation_barber.dmm"]
required_map = "MetaStation"
coordinates = [101, 117, 1]

# Metastation Armory
[templates.metastation_armory]
map_files = ["metastation_armory.dmm"]
required_map = "MetaStation"
coordinates = [101, 170, 1]
