# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.

# METASTATION MAP TEMPLATES
# Metastation Arrivals
[templates.metastaton_arrivals]
map_files = ["metastation_arrivals.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [20, 107, 1]
trait_name = "Station"

# Metastation Orderly Post
[templates.metastation_orderly_post]
map_files = ["metastation_orderly_post.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [92, 107, 1]
trait_name = "Station"

# Metastation Science Post
[templates.metastation_science_post]
map_files = ["metastation_science_post.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [123, 95, 1]
trait_name = "Station"

# Metastation Engineering Post
[templates.metastation_engineering_post]
map_files = ["metastation_engineering_post.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [164, 131, 1]
trait_name = "Station"

# Metastation Cargo Post
[templates.metastation_cargo_post]
map_files = ["metastation_cargo_post.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [71, 155, 1]
trait_name = "Station"

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [136, 181, 1]
trait_name = "Station"

# Metastation Barber
[templates.metastation_barber]
map_files = ["metastation_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [101, 117, 1]
trait_name = "Station"

# Metastation Armory
[templates.metastation_armory]
map_files = ["metastation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation"
required_map = "MetaStation.dmm"
coordinates = [101, 170, 1]
trait_name = "Station"

# DELTASTATION MAP EDITS
# Deltastation Arrivals
[templates.deltastation_arrivals]
map_files = ["deltastation_arrivals.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [126, 195, 1]
trait_name = "Station"

# Deltastation Science Post
[templates.deltastation_science_post]
map_files = ["deltastation_science_post.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [132, 93, 1]
trait_name = "Station"

# Deltastation Engineering Post
[templates.deltastation_engineering_post]
map_files = ["deltastation_engineering_post.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [103, 128, 1]
trait_name = "Station"

# Deltastation Medical Post
[templates.deltastation_medical_post]
map_files = ["deltastation_medical_post.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [172, 92, 1]
trait_name = "Station"

# Deltastation Cargo Post
[templates.deltastation_cargo_post]
map_files = ["deltastation_cargo_post.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [161, 163, 1]
trait_name = "Station"

# Deltastation Cryo
[templates.deltastation_cryo]
map_files = ["deltastation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [215, 93, 1]
trait_name = "Station"

# Deltastation Armory
[templates.deltastation_armory]
map_files = ["deltastation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [206, 127, 1]
trait_name = "Station"

# Deltastation Barber
[templates.deltastation_barber]
map_files = ["deltastation_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [215, 93, 1]
trait_name = "Station"

# Deltastation Prison
[templates.deltastation_prison]
map_files = ["deltastation_prison.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation"
required_map = "DeltaStation2.dmm"
coordinates = [189, 154, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
[templates.icebox_arrivals]
map_files = ["icebox_arrivals.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox"
required_map = "IceBoxStation.dmm"
coordinates = [10, 116, 3]
trait_name = "Station"
